services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  app:
    build:
      context: .
    container_name: my_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${APP_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SMTP: ${SMTP}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_GMAIL_USER: ${SMTP_GMAIL_USER}
      SMTP_GMAIL_PASS: ${SMTP_GMAIL_PASS}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    command: >
      bash -c "
        until mysql -h db -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} -e 'show tables'; do
          echo 'Waiting for MySQL to be ready...';
          sleep 10;
        done;
        php /var/www/html/sql/install.php;
        apache2-foreground
      "

volumes:
  db_data:
